name: Build OpenJDK 21 for Android aarch64

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 */2 *'

jobs:
  build_android:
    name: "Build for Android aarch64"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build with CI build script
      run: bash "ci_build_arch_aarch64.sh"
    - name: Upload JRE build output
      uses: actions/upload-artifact@v2
      with:
        name: 'jre21-aarch64'
        path: jre21*.tar.xz
