name: Build OpenJDK 8 for Android aarch64

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */2 *'

jobs:
  build_android:
    name: "Build for Android aarch64"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Build with CI build script
      run: |
        sudo apt update
        sudo apt -y install autoconf python unzip zip
        sudo apt -y install systemtap-sdt-dev gcc-multilib g++-multilib libxtst-dev libasound2-dev libelf-dev libfontconfig1-dev libx11-dev
        bash "ci_build_arch_aarch64.sh"
    - name: Upload JDK build output
      uses: actions/upload-artifact@v2
      with:
        name: "jdk8-aarch64"
        path: jdk8*.tar.xz

    - name: Setup tmate session if failed
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

    - name: Upload JRE build output
      uses: actions/upload-artifact@v2
      with:
        name: 'jre8-aarch64'
        path: jre8*.tar.xz
    - name: Upload JRE debuginfo build output
      uses: actions/upload-artifact@v2
      with:
        name: "jre8-debuginfo-aarch64"
        path: dizout

  pojav:
    needs: build_android
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get jre8-aarch64
      uses: actions/download-artifact@v2
      with:
        name: jre8-aarch64
        path: pojav
    - name: Repack JRE
      run: bash "repackjre.sh" $GITHUB_WORKSPACE/pojav $GITHUB_WORKSPACE/pojav/jre8-pojav
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: jre8-pojav
          path: pojav/jre8-pojav/*
